### ISSUE TITLE
testServer 구현

### ISSUE THREAD

**Issue by faulty337** [instantDuo/CodeSwitching-BE#2]
# Description

testServer 구현

## Todo
- [ ] Swagger 추가
- [ ] 회원가입 test API 구현
- [ ] 로그인 test API 구현
- [ ] NBack 게임 API 구현
- [ ] Stroop 게임 API 구현
