### ISSUE TITLE
NBack 게임 구현

### ISSUE THREAD

**Issue by faulty337** [instantDuo/CodeSwitching-BE#6]
# Description

NBack 게임 플레이를 위한 정보 반환 및 플레이 데이터 기록, 결과 반환 구현

## Todo

- [ ] Entity 구현(NBackData, NBackParticipant)
- [ ] Repository 구현
- [ ] Service 구현
- [ ] NBack 플레이 로직 구현
- [ ] Redis 연동
- [ ] 임시 데이터 생성
- [ ] 결과 반환

## Etc

기타사항
